run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gofmt
    - goimports
    - structcheck
    - unused
    - deadcode

linters-settings:
  gofmt:
    simplify: true

issues:
  exclude-use-default: false
